# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalDialogBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject

import SetupFile


class Ui_Form(QObject):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setMaximumSize(343, 169)
        Form.setWindowModality(2)  # set modal mode
        Form.setStyleSheet(SetupFile.Background)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.Text = QtWidgets.QLabel(Form)
        self.Text.setObjectName("Text")
        self.verticalLayout.addWidget(self.Text)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.OkButton = QtWidgets.QPushButton(Form)
        self.OkButton.setObjectName("OkButton")
        self.OkButton.setStyleSheet(SetupFile.Button)
        self.horizontalLayout.addWidget(self.OkButton)

        self.CancelButton = QtWidgets.QPushButton(Form)
        self.CancelButton.setObjectName("CancelButton")
        self.CancelButton.setStyleSheet(SetupFile.Button)

        self.horizontalLayout.addWidget(self.CancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Form", "Form"))
        self.OkButton.setText(_translate("Form", "OK"))
        self.CancelButton.setText(_translate("Form", "Cancel"))

    def setText(self, Text):
        self.Text.setText(Text)

class MyWindow(QtWidgets.QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.OkButton.clicked.connect(self.close)
        self.CancelButton.clicked.connect(self.close)


