# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalImport.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject
from PyQt5.QtWidgets import QFileDialog

import SetupFile
from Database import Investment,Statement


class Ui_Form(QObject):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(681, 430)
        self.Investment = Investment.Investment()
        self.Statement= Statement.Statement()
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.GenerateTemplateFor_Text = QtWidgets.QLabel(Form)
        self.GenerateTemplateFor_Text.setObjectName("GenerateTemplateFor_Text")
        self.horizontalLayout_5.addWidget(self.GenerateTemplateFor_Text)
        self.GenerateTemplateFor = QtWidgets.QComboBox(Form)
        self.GenerateTemplateFor.setObjectName("GenerateTemplateFor")
        self.horizontalLayout_5.addWidget(self.GenerateTemplateFor)
        self.GenerateButton = QtWidgets.QPushButton(Form)
        self.GenerateButton.setObjectName("GenerateButton")
        self.horizontalLayout_5.addWidget(self.GenerateButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImportInvestment_Text = QtWidgets.QLabel(Form)
        self.ImportInvestment_Text.setObjectName("ImportInvestment_Text")
        self.horizontalLayout.addWidget(self.ImportInvestment_Text)
        self.ImportInvestment = QtWidgets.QPushButton(Form)
        self.ImportInvestment.setObjectName("ImportInvestment")
        self.horizontalLayout.addWidget(self.ImportInvestment)
        self.InvestmentPath = QtWidgets.QLabel(Form)
        self.InvestmentPath.setObjectName("InvestmentPath")
        self.InvestmentPath.setMinimumWidth(200)
        self.horizontalLayout.addWidget(self.InvestmentPath)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImportStatement_Text = QtWidgets.QLabel(Form)
        self.ImportStatement_Text.setObjectName("ImportStatement_Text")
        self.horizontalLayout_2.addWidget(self.ImportStatement_Text)
        self.ImportStatement = QtWidgets.QPushButton(Form)
        self.ImportStatement.setObjectName("ImportStatement")
        self.horizontalLayout_2.addWidget(self.ImportStatement)
        self.StatementPath = QtWidgets.QLabel(Form)
        self.StatementPath.setObjectName("StatementPath")
        self.StatementPath.setMinimumWidth(200)
        self.horizontalLayout_2.addWidget(self.StatementPath)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.ImportButton = QtWidgets.QPushButton(Form)
        self.ImportButton.setObjectName("ImportButton")
        self.horizontalLayout_3.addWidget(self.ImportButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.Action = QtWidgets.QLabel(Form)
        self.Action.setObjectName("Action")
        self.horizontalLayout_4.addWidget(self.Action)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.Action.setHidden(True)
        self.GenerateTemplateFor.addItem("Investment")
        self.GenerateTemplateFor.addItem("Statement")
        self.ImportStatement.clicked.connect(self.ImportStatement1)
        self.ImportInvestment.clicked.connect(self.ImportInvestment1)
        self.GenerateButton.clicked.connect(self.generateTemplate)
        self.ImportButton.clicked.connect(self.Import)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.GenerateTemplateFor_Text.setText(_translate("Form", "Generate template for: "))
        self.GenerateButton.setText(_translate("Form", "Generate"))
        self.ImportInvestment_Text.setText(_translate("Form", "Import investment: "))
        self.ImportInvestment.setText(_translate("Form", "Import"))
        self.ImportStatement_Text.setText(_translate("Form", "Import statement: "))
        self.ImportStatement.setText(_translate("Form", "Import"))
        self.ImportButton.setText(_translate("Form", "Import"))
        self.Action.setText(_translate("Form", "TextLabel"))


    def setProfile(self,Profile):
        """Select profile."""
        self.Profile= Profile

    def generateTemplate(self):
        """Generate appropriate template."""
        if self.GenerateTemplateFor.currentIndex() == 0:
            Investment.Investment().createExcelTemplate()
            os.startfile("Investment.xlsx")
        else:
            Statement.Statement().createExcelTemplate()
            os.startfile("Statement.xlsx")

    def ImportInvestment1(self):
        """Import investment"""
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly
        filename = QFileDialog.getOpenFileName(None, 'Investment',
                                               "", "Excel Work Book(*.xlsx)", options=options)
        path = filename[0]
        if not len(path) == 0:
            self.InvestmentPath.setText(path)
        else:
            self.InvestmentPath.setText("")

    def ImportStatement1(self):
        """Import statement"""
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly
        filename = QFileDialog.getOpenFileName(None, 'Statement',
                                               "", "Excel Work Book(*.xlsx)", options=options)
        path = filename[0]
        if not len(path) == 0:
            self.StatementPath.setText(path)
        else:
            self.StatementPath.setText("")

    def Import(self):
        """Import one, or both files."""
        if not self.InvestmentPath.text() == "":
            self.Investment.setProfile(self.Profile)
            self.Action.setText("")
            if self.Investment.isFileFormatCorrect(self.InvestmentPath.text()):
                self.Action.setText("")
            else:
                self.Action.setText("Something wrong")
                self.Action.setHidden(False)
                return

        if not self.StatementPath.text() == "":
            self.Statement.setProfile(self.Profile)
            self.Action.setText("")
            if self.Statement.isFileFormatCorrect(self.StatementPath.text()):
                self.Action.setText("")
            else:
                self.Action.setText("Something wrong")
                self.Action.setHidden(False)
                return

        if not self.InvestmentPath.text() == "":
            self.Investment.ImportFromExcel(self.InvestmentPath.text())
        if not self.StatementPath.text() == "":
            self.Statement.ImportFromExcel(self.StatementPath.text())




class MyWindow(QtWidgets.QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.setWindowTitle("Import")
        self.setStyleSheet(SetupFile.Background)
        self.GenerateTemplateFor.setStyleSheet(SetupFile.ComboBox)
        self.GenerateButton.setStyleSheet(SetupFile.Button)
        self.ImportStatement.setStyleSheet(SetupFile.Button)
        self.ImportInvestment.setStyleSheet(SetupFile.Button)
        self.ImportButton.setStyleSheet(SetupFile.Button)
        self.InvestmentPath.setStyleSheet(SetupFile.NoChangeTextColor)
        self.StatementPath.setStyleSheet(SetupFile.NoChangeTextColor)

