# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalImport.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject
from PyQt5.QtWidgets import QFileDialog
from Database import Investment,Statement


class Ui_Form(QObject):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(681, 430)
        self.Investment = Investment.Investment()
        self.Statement= Statement.Statement()
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.GenerateTemplateFor_Text = QtWidgets.QLabel(Form)
        self.GenerateTemplateFor_Text.setObjectName("GenerateTemplateFor_Text")
        self.horizontalLayout_5.addWidget(self.GenerateTemplateFor_Text)
        self.GenerateTemplateFor = QtWidgets.QComboBox(Form)
        self.GenerateTemplateFor.setObjectName("GenerateTemplateFor")
        self.GenerateTemplateFor.addItem("Investment")
        self.GenerateTemplateFor.addItem("Statement")
        self.horizontalLayout_5.addWidget(self.GenerateTemplateFor)
        self.GenerateButton = QtWidgets.QPushButton(Form)
        self.GenerateButton.setObjectName("GenerateButton")
        self.horizontalLayout_5.addWidget(self.GenerateButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImportInvestment_Text = QtWidgets.QLabel(Form)
        self.ImportInvestment_Text.setObjectName("ImportInvestment_Text")
        self.horizontalLayout.addWidget(self.ImportInvestment_Text)
        self.ImportInvestment = QtWidgets.QPushButton(Form)
        self.ImportInvestment.setObjectName("ImportInvestment")
        self.horizontalLayout.addWidget(self.ImportInvestment)
        self.InvestmentPath = QtWidgets.QLabel(Form)
        self.InvestmentPath.setObjectName("InvestmentPath")
        self.horizontalLayout.addWidget(self.InvestmentPath)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImportStatement_Text = QtWidgets.QLabel(Form)
        self.ImportStatement_Text.setObjectName("ImportStatement_Text")
        self.horizontalLayout_2.addWidget(self.ImportStatement_Text)
        self.ImportStatement = QtWidgets.QPushButton(Form)
        self.ImportStatement.setObjectName("ImportStatement")
        self.horizontalLayout_2.addWidget(self.ImportStatement)
        self.StatementPath = QtWidgets.QLabel(Form)
        self.StatementPath.setObjectName("StatementPath")
        self.horizontalLayout_2.addWidget(self.StatementPath)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.ImportButton = QtWidgets.QPushButton(Form)
        self.ImportButton.setObjectName("ImportButton")
        self.horizontalLayout_3.addWidget(self.ImportButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.Action = QtWidgets.QLabel(Form)
        self.Action.setObjectName("Action")
        self.horizontalLayout_4.addWidget(self.Action)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.ImportStatement.clicked.connect(self.ImportStatement1)
        self.ImportInvestment.clicked.connect(self.ImportInvestment1)
        self.GenerateButton.clicked.connect(self.generateTemplate)
        self.ImportButton.clicked.connect(self.Import)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.GenerateTemplateFor_Text.setText(_translate("Form", "Generate template for: "))
        self.GenerateButton.setText(_translate("Form", "Generate"))
        self.ImportInvestment_Text.setText(_translate("Form", "Import investment: "))
        self.ImportInvestment.setText(_translate("Form", "Import"))
        self.ImportStatement_Text.setText(_translate("Form", "Import statement: "))
        self.ImportStatement.setText(_translate("Form", "Import"))
        self.ImportButton.setText(_translate("Form", "Import"))

    def setProfile(self,Profile):
        self.Profile= Profile

    def generateTemplate(self):
        if self.GenerateTemplateFor.currentIndex() == 0:
            Investment.Investment().createExcelTemplate()
            os.startfile("Investment.xlsx")
            print("investment")
        else:
            Statement.Statement().createExcelTemplate()
            os.startfile("Statement.xlsx")
            print("statement")

    def ImportInvestment1(self):
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly
        filename = QFileDialog.getOpenFileName(None, 'Investment',
                                               "", "Excel Work Book(*.xlsx)", options=options)
        path = filename[0]
        if not len(path) == 0:
            self.InvestmentPath.setText(path)
        else:
            self.InvestmentPath.setText("")

    def ImportStatement1(self):
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly
        filename = QFileDialog.getOpenFileName(None, 'Statement',
                                               "", "Excel Work Book(*.xlsx)", options=options)
        path = filename[0]
        if not len(path) == 0:
            self.StatementPath.setText(path)
        else:
            self.StatementPath.setText("")

    def Import(self):
        if not self.InvestmentPath.text() == "":
            self.Investment.setProfile(self.Profile)
            self.Action.setText("")
            if self.Investment.isFileFormatCorrect(self.InvestmentPath.text()):
                self.Action.setText("")
            else:
                self.Action.setText("Something wrong")
                return

        if not self.StatementPath.text() == "":
            self.Statement.setProfile(self.Profile)
            self.Action.setText("")
            if self.Statement.isFileFormatCorrect(self.StatementPath.text()):
                self.Action.setText("")
            else:
                self.Action.setText("Something wrong")
                return

        if not self.InvestmentPath.text() == "":
            self.Investment.ImportFromExcel(self.InvestmentPath.text())
        if not self.StatementPath.text() == "":
            self.Statement.ImportFromExcel(self.StatementPath.text())




class MyWindow(QtWidgets.QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
