# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalStatistics1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import pickle
import calendar
from datetime import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QDate
from PyQt5.QtWidgets import QCalendarWidget

from Database import Statement, Log, Investment

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.dates as mdates
from matplotlib.figure import Figure
from matplotlib.patches import Patch
import matplotlib.ticker as ticker


class MplCanvas(FigureCanvas):

    def __init__(self, parent=None, width=4, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)


class Ui_Form(QObject):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1040, 710)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Mode_Text = QtWidgets.QLabel(Form)
        self.Mode_Text.setObjectName("Mode_Text")
        self.horizontalLayout.addWidget(self.Mode_Text)
        self.Mode = QtWidgets.QComboBox(Form)
        self.Mode.setObjectName("Mode")
        self.horizontalLayout.addWidget(self.Mode)

        self.Date = QtWidgets.QDateEdit()
        self.Date.setDisplayFormat("MM-yyyy")
        self.Date.setCalendarPopup(True)
        self.Date.setMaximumDate(QDate.currentDate())
        self.Date.setDateTime(QtCore.QDateTime.currentDateTime())
        self.horizontalLayout.addWidget(self.Date)

        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, 10, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LayoutForMoney = QtWidgets.QVBoxLayout()
        self.LayoutForMoney.setContentsMargins(10, 10, 10, 10)
        self.LayoutForMoney.setSpacing(10)
        self.LayoutForMoney.setObjectName("LayoutForMoney")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.LayoutForMoney.addItem(spacerItem1)
        self.LayoutMoneyDeposited = QtWidgets.QHBoxLayout()
        self.LayoutMoneyDeposited.setObjectName("LayoutMoneyDeposited")
        self.MoneyDeposited_Text = QtWidgets.QLabel(Form)
        self.MoneyDeposited_Text.setObjectName("MoneyDeposited_Text")
        self.LayoutMoneyDeposited.addWidget(self.MoneyDeposited_Text)
        self.MoneyDeposited = QtWidgets.QLabel(Form)
        self.MoneyDeposited.setObjectName("MoneyDeposited")
        self.LayoutMoneyDeposited.addWidget(self.MoneyDeposited)
        self.MoneyDepositedChange = QtWidgets.QLabel(Form)
        self.MoneyDepositedChange.setObjectName("MoneyDepositedChange")
        self.LayoutMoneyDeposited.addWidget(self.MoneyDepositedChange)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LayoutMoneyDeposited.addItem(spacerItem2)
        self.LayoutForMoney.addLayout(self.LayoutMoneyDeposited)
        self.LayoutMoneyWithdrawn = QtWidgets.QHBoxLayout()
        self.LayoutMoneyWithdrawn.setObjectName("LayoutMoneyWithdrawn")
        self.MoneyWithdrawn_Text = QtWidgets.QLabel(Form)
        self.MoneyWithdrawn_Text.setObjectName("MoneyWithdrawn_Text")
        self.LayoutMoneyWithdrawn.addWidget(self.MoneyWithdrawn_Text)
        self.MoneyWithdrawn = QtWidgets.QLabel(Form)
        self.MoneyWithdrawn.setObjectName("MoneyWithdrawn")
        self.LayoutMoneyWithdrawn.addWidget(self.MoneyWithdrawn)
        self.MoneyWithdrawnChange = QtWidgets.QLabel(Form)
        self.MoneyWithdrawnChange.setObjectName("MoneyWithdrawnChange")
        self.LayoutMoneyWithdrawn.addWidget(self.MoneyWithdrawnChange)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LayoutMoneyWithdrawn.addItem(spacerItem3)
        self.LayoutForMoney.addLayout(self.LayoutMoneyWithdrawn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.LayoutForMoney.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.LayoutForMoney)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)

        self.canvas = MplCanvas(self, height=300, width=600, dpi=100)
        self.canvas.setMinimumSize(QtCore.QSize(600, 300))
        self.canvas.setObjectName("canvas")
        self.horizontalLayout_3.addWidget(self.canvas)

        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, 10, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LayoutForMoney_ = QtWidgets.QVBoxLayout()
        self.LayoutForMoney_.setContentsMargins(10, 10, 10, 10)
        self.LayoutForMoney_.setSpacing(10)
        self.LayoutForMoney_.setObjectName("LayoutForMoney_")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.LayoutForMoney_.addItem(spacerItem7)
        self.InvestmentMadeLoayout = QtWidgets.QHBoxLayout()
        self.InvestmentMadeLoayout.setObjectName("InvestmentMadeLoayout")
        self.InvestmentMade_Text = QtWidgets.QLabel(Form)
        self.InvestmentMade_Text.setObjectName("InvestmentMade_Text")
        self.InvestmentMadeLoayout.addWidget(self.InvestmentMade_Text)
        self.InvestmentMade = QtWidgets.QLabel(Form)
        self.InvestmentMade.setObjectName("InvestmentMade")
        self.InvestmentMadeLoayout.addWidget(self.InvestmentMade)
        self.InvestmentMadeChange = QtWidgets.QLabel(Form)
        self.InvestmentMadeChange.setObjectName("InvestmentMadeChange")
        self.InvestmentMadeLoayout.addWidget(self.InvestmentMadeChange)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.InvestmentMadeLoayout.addItem(spacerItem8)
        self.LayoutForMoney_.addLayout(self.InvestmentMadeLoayout)
        self.InvestmentSoldLayout = QtWidgets.QHBoxLayout()
        self.InvestmentSoldLayout.setObjectName("InvestmentSoldLayout")
        self.InvestmentSold_Text = QtWidgets.QLabel(Form)
        self.InvestmentSold_Text.setObjectName("InvestmentSold_Text")
        self.InvestmentSoldLayout.addWidget(self.InvestmentSold_Text)
        self.InvestmentSold = QtWidgets.QLabel(Form)
        self.InvestmentSold.setObjectName("InvestmentSold")
        self.InvestmentSoldLayout.addWidget(self.InvestmentSold)
        self.InvestmentSoldChange = QtWidgets.QLabel(Form)
        self.InvestmentSoldChange.setObjectName("InvestmentSoldChange")
        self.InvestmentSoldLayout.addWidget(self.InvestmentSoldChange)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.InvestmentSoldLayout.addItem(spacerItem9)
        self.LayoutForMoney_.addLayout(self.InvestmentSoldLayout)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.LayoutForMoney_.addWidget(self.line_2)
        self.GoldBoughtLayout = QtWidgets.QHBoxLayout()
        self.GoldBoughtLayout.setObjectName("GoldBoughtLayout")
        self.GoldBought_Text = QtWidgets.QLabel(Form)
        self.GoldBought_Text.setObjectName("GoldBought_Text")
        self.GoldBoughtLayout.addWidget(self.GoldBought_Text)
        self.GoldBought = QtWidgets.QLabel(Form)
        self.GoldBought.setObjectName("GoldBought")
        self.GoldBoughtLayout.addWidget(self.GoldBought)
        self.GoldBoughtChange = QtWidgets.QLabel(Form)
        self.GoldBoughtChange.setObjectName("GoldBoughtChange")
        self.GoldBoughtLayout.addWidget(self.GoldBoughtChange)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.GoldBoughtLayout.addItem(spacerItem10)
        self.LayoutForMoney_.addLayout(self.GoldBoughtLayout)
        self.GoldSoldLayout = QtWidgets.QHBoxLayout()
        self.GoldSoldLayout.setObjectName("GoldSoldLayout")
        self.GoldSold_Text = QtWidgets.QLabel(Form)
        self.GoldSold_Text.setObjectName("GoldSold_Text")
        self.GoldSoldLayout.addWidget(self.GoldSold_Text)
        self.GoldSold = QtWidgets.QLabel(Form)
        self.GoldSold.setObjectName("GoldSold")
        self.GoldSoldLayout.addWidget(self.GoldSold)
        self.GoldSoldChange = QtWidgets.QLabel(Form)
        self.GoldSoldChange.setObjectName("GoldSoldChange")
        self.GoldSoldLayout.addWidget(self.GoldSoldChange)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.GoldSoldLayout.addItem(spacerItem11)
        self.LayoutForMoney_.addLayout(self.GoldSoldLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.LayoutForMoney_.addWidget(self.line)
        self.AverageProfitLossLayout = QtWidgets.QHBoxLayout()
        self.AverageProfitLossLayout.setObjectName("AverageProfitLossLayout")
        self.AverageProfitLoss_Text = QtWidgets.QLabel(Form)
        self.AverageProfitLoss_Text.setObjectName("AverageProfitLoss_Text")
        self.AverageProfitLossLayout.addWidget(self.AverageProfitLoss_Text)
        self.AverageProfitLoss = QtWidgets.QLabel(Form)
        self.AverageProfitLoss.setObjectName("AverageProfitLoss")
        self.AverageProfitLossLayout.addWidget(self.AverageProfitLoss)
        self.AverageProfitLossChange = QtWidgets.QLabel(Form)
        self.AverageProfitLossChange.setObjectName("AverageProfitLossChange")
        self.AverageProfitLossLayout.addWidget(self.AverageProfitLossChange)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.AverageProfitLossLayout.addItem(spacerItem12)
        self.LayoutForMoney_.addLayout(self.AverageProfitLossLayout)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.LayoutForMoney_.addItem(spacerItem13)
        self.horizontalLayout_4.addLayout(self.LayoutForMoney_)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.yaxis_text = QtWidgets.QLabel(Form)
        self.yaxis_text.setObjectName("yaxis_text")
        self.horizontalLayout_2.addWidget(self.yaxis_text)
        self.yaxis = QtWidgets.QComboBox(Form)
        self.yaxis.setObjectName("yaxis")
        self.horizontalLayout_2.addWidget(self.yaxis)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.canvas1 = MplCanvas(self, height=300, width=600, dpi=100)
        self.canvas1.setMinimumSize(QtCore.QSize(600, 300))
        self.canvas1.setObjectName("canvas")
        self.verticalLayout.addWidget(self.canvas1)

        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.Mode.currentIndexChanged.connect(self.updateDateEdit)
        self.Date.dateChanged.connect(self.updateGraph)
        self.SetupPage()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Mode_Text.setText(_translate("Form", "Mode: "))
        self.MoneyDeposited_Text.setText(_translate("Form", "Money deposited:"))
        self.MoneyDepositedChange.setText(_translate("Form", "+50.1"))
        self.MoneyWithdrawn_Text.setText(_translate("Form", "Money withdrawn:"))
        self.MoneyWithdrawnChange.setText(_translate("Form", "+50.1"))
        self.InvestmentMade_Text.setText(_translate("Form", "Investment made : "))
        self.InvestmentMade.setText(_translate("Form", "12000"))
        self.InvestmentMadeChange.setText(_translate("Form", "+50.1"))
        self.InvestmentSold_Text.setText(_translate("Form", "Investment sold : "))
        self.InvestmentSold.setText(_translate("Form", "12000"))
        self.InvestmentSoldChange.setText(_translate("Form", "+50.1"))
        self.GoldBought_Text.setText(_translate("Form", "Gold bought : "))
        self.GoldBought.setText(_translate("Form", "12000"))
        self.GoldBoughtChange.setText(_translate("Form", "+50.1"))
        self.GoldSold_Text.setText(_translate("Form", "Gold sold : "))
        self.GoldSold.setText(_translate("Form", "12000"))
        self.GoldSoldChange.setText(_translate("Form", "+50.1"))
        self.AverageProfitLoss_Text.setText(_translate("Form", "Average profit/loss : "))
        self.AverageProfitLoss.setText(_translate("Form", "12000"))
        self.AverageProfitLossChange.setText(_translate("Form", "+50.1"))
        self.yaxis_text.setText(_translate("Form", "TextLabel"))

    def updateDateEdit(self):
        if self.Mode.currentIndex() == 0:
            self.Date.setDisplayFormat("MM-yyyy")
            self.Date.setEnabled(True)
        elif self.Mode.currentIndex() == 1:
            self.Date.setDisplayFormat("yyyy")
            self.Date.setEnabled(True)
        elif self.Mode.currentIndex() == 2:
            self.Date.setEnabled(False)

    def updateGraph(self):
        self.BarGraph()
        self.canvas.draw()
        days_in_month = calendar.monthrange(self.Date.date().year(), self.Date.date().month())[1]
        start_date = datetime(self.Date.date().year(), self.Date.date().month(), 1).date()
        end_date = datetime(self.Date.date().year(), self.Date.date().month(), days_in_month).date()
        self.MoneyDeposited.setText(str(self.Log.getMoneyAdded(StartDate=start_date, EndDate=end_date)))
        self.MoneyWithdrawn.setText(str(self.Log.getMoneyOut(StartDate=start_date, EndDate=end_date)))

    def SetupPage(self):
        with open("my_variable.pickle", "rb") as f:
            UserID = pickle.load(f)
        self.Investment = Investment.Investment()
        self.Statement = Statement.Statement()
        self.Log = Log.Log.Money()

        self.Investment.setProfile(UserID)
        self.Statement.setProfile(UserID)
        self.Log.setProfile(UserID)
        days_in_month = calendar.monthrange(self.Date.date().year(), self.Date.date().month())[1]
        start_date = datetime(self.Date.date().year(), self.Date.date().month(), 1).date()
        end_date = datetime(self.Date.date().year(), self.Date.date().month(), days_in_month).date()
        self.MoneyDeposited.setText(str(self.Log.getMoneyAdded(StartDate=start_date, EndDate=end_date)))
        self.MoneyWithdrawn.setText(str(self.Log.getMoneyOut(StartDate=start_date, EndDate=end_date)))

        self.BarGraph()

    def BarGraph(self):
        self.canvas.axes.clear()
        self.Statement.getProfitLossData(self.Date.date().year(), self.Date.date().month())
        Add, Withdrawn = self.Log.getDatesInWeekFormatForMonth(self.Date.date().year(), self.Date.date().month())

        labels = list(Add.keys())
        y = list(Add.values())
        y1 = list(Withdrawn.values())

        self.canvas.axes.bar(labels, y, width=0.3, align='center', label='Data 1', color="Green")
        self.canvas.axes.bar(labels, y1, width=0.3, align='center', label='Data 2', color="Red")

        self.canvas.axes.set_xlabel('Date')
        self.canvas.axes.set_ylabel('Money')

        # Create a custom legend
        legend_elements = [Patch(facecolor='g', edgecolor='black', label='Money Added'),
                           Patch(facecolor='r', edgecolor='black', label='Money Withdrawn')]
        self.canvas.axes.legend(handles=legend_elements)


class MyWindow(QtWidgets.QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
