# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GoldCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject

from GoldRate import Gold


class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Purity_Text = QtWidgets.QLabel(self.centralwidget)
        self.Purity_Text.setObjectName("Purity_Text")
        self.horizontalLayout_4.addWidget(self.Purity_Text)
        self.Purity = QtWidgets.QComboBox(self.centralwidget)
        self.Purity.setObjectName("Purity")
        self.Purity.addItem("")
        self.Purity.addItem("")
        self.Purity.addItem("")
        self.Purity.addItem("")
        self.Purity.addItem("")
        self.Purity.addItem("")
        self.Purity.addItem("")
        self.Purity.addItem("")
        self.Purity.addItem("")
        self.horizontalLayout_4.addWidget(self.Purity)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Gold_Text = QtWidgets.QLabel(self.centralwidget)
        self.Gold_Text.setObjectName("Gold_Text")
        self.horizontalLayout.addWidget(self.Gold_Text)
        self.Gold = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Gold.setKeyboardTracking(True)
        self.Gold.setObjectName("Gold")
        self.horizontalLayout.addWidget(self.Gold)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("password_Text")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Cost = QtWidgets.QLabel(self.centralwidget)
        self.Cost.setObjectName("Cost")
        self.horizontalLayout_3.addWidget(self.Cost)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Check = QtWidgets.QPushButton(self.centralwidget)
        self.Check.setObjectName("Check")
        self.horizontalLayout_2.addWidget(self.Check)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Purity_Text.setText(_translate("MainWindow", "Purity:"))
        self.Purity.setItemText(0, _translate("MainWindow", "24K"))
        self.Purity.setItemText(1, _translate("MainWindow", "22K"))
        self.Purity.setItemText(2, _translate("MainWindow", "21K"))
        self.Purity.setItemText(3, _translate("MainWindow", "18K"))
        self.Purity.setItemText(4, _translate("MainWindow", "16K"))
        self.Purity.setItemText(5, _translate("MainWindow", "14K"))
        self.Purity.setItemText(6, _translate("MainWindow", "12K"))
        self.Purity.setItemText(7, _translate("MainWindow", "10K"))
        self.Purity.setItemText(8, _translate("MainWindow", "9K"))
        self.Gold_Text.setText(_translate("MainWindow", "Gold :"))
        self.label_3.setText(_translate("MainWindow", "Cost: "))
        self.Cost.setText(_translate("MainWindow", "0"))
        self.Check.setText(_translate("MainWindow", "Check"))

    def getRate(self, Rate, Currency, Unit, DecimalPoint):
        self.Gold1 = Gold(Currency=Currency, Unit=Unit)
        if self.Purity.currentIndex() == 0:
            Purity = 24
        if self.Purity.currentIndex() == 1:
            Purity = 22
        if self.Purity.currentIndex() == 2:
            Purity = 21
        if self.Purity.currentIndex() == 3:
            Purity = 18
        if self.Purity.currentIndex() == 4:
            Purity = 16
        if self.Purity.currentIndex() == 5:
            Purity = 14
        if self.Purity.currentIndex() == 6:
            Purity = 12
        if self.Purity.currentIndex() == 7:
            Purity = 10
        if self.Purity.currentIndex() == 8:
            Purity = 9
        self.Gold1.getLatestExchangeRate()
        # if Currency != "$":
        #     Rate = self.Gold1.convertRateTo(Rate)
        self.Cost.setText(str(round(
            Rate*self.Gold1.convertGtoDifferentUnit(self.Gold.value()) * (Purity / 24),
            DecimalPoint)))


class MyWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
