# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import datetime
import pickle

import matplotlib
from PyQt5.QtCore import QObject

matplotlib.use('Qt5Agg')

from PyQt5 import QtCore, QtWidgets
from datetime import datetime

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.dates as mdates
from matplotlib.figure import Figure


def strToDate(date_string):
    # date_string = "2022-03-05"
    date_format = "%Y-%m-%d"
    date_object = datetime.strptime(date_string, date_format)
    return date_object


class MplCanvas(FigureCanvas):

    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)


class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 649)
        self.main = QtWidgets.QWidget(MainWindow)
        self.main.setObjectName("main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SeeBy = QtWidgets.QVBoxLayout()
        self.SeeBy.setObjectName("SeeBy")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.SeeBy.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.canvas = MplCanvas(self, width=5, height=4, dpi=100)
        self.canvas.setMinimumSize(QtCore.QSize(500, 500))
        self.canvas.setObjectName("canvas")
        self.verticalLayout.addWidget(self.canvas)
        self.pie()
        self.SeeBy.addLayout(self.verticalLayout)
        self.BottomLayout = QtWidgets.QVBoxLayout()
        self.BottomLayout.setObjectName("BottomLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # self.label_2 = QtWidgets.QLabel(self.main)
        # self.label_2.setObjectName("label_2")
        # self.horizontalLayout_2.addWidget(self.label_2)
        # self.comboBox_2 = QtWidgets.QComboBox(self.main)
        # self.comboBox_2.setObjectName("comboBox_2")
        # self.horizontalLayout_2.addWidget(self.comboBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.BottomLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.BottomLayout.addLayout(self.horizontalLayout_3)
        self.SeeBy.addLayout(self.BottomLayout)
        self.verticalLayout_3.addLayout(self.SeeBy)
        MainWindow.setCentralWidget(self.main)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def pie(self):
        from Database import User,Investment
        with open("my_variable.pickle", "rb") as f:
            UserID = pickle.load(f)
        Gold = Investment.Investment()
        Gold.setProfile(UserID)
        Money = User.User()
        Money.SelectProfile(UserID)
        data = Money.getDataForGraph()
        print(data)
        # print(data)
        # data = {'C': 20, 'C++': 15, 'Java': 30,
        #         'Python': 35}
        # courses = list(data.keys())
        # values = list(data.values())
        data_without_zero = {k: v for k, v in data.items() if v > 0}
        names = list(data_without_zero.keys())
        values = list(data_without_zero.values())
        # explode = (0.1,0.1)
        wp = {'linewidth': 1, 'edgecolor': "black"}
        _, _, autotexts = self.canvas.axes.pie(values, labels=[''] * len(values), shadow=True, autopct='%1.1f%%',
                                               wedgeprops=wp, pctdistance=1.3)
        # create legend labels with percentages
        # Generate legend labels with extra information for 'Gold'
        legend_labels = []
        for i, label in enumerate(names):
            if label == 'GoldMoney':
                extra_info =str(Gold.getTotalGold())+ " g"  # Example extra information
                legend_labels.append(f'{label} ({values[i]:.1f}, {extra_info})')
            else:
                legend_labels.append(f'{label} ({values[i]:.1f})')

        self.canvas.axes.legend(legend_labels, loc='best')
        # self.canvas.axes.legend(bars, names, loc="best")


class MyWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
